server:
  port: 8080
  servlet:
    contextPath: /v1/api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/haruhanal?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: haruhanal-user-pool

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: create
    open-in-view: false
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /static/**

logging.level:
  org.hibernate.SQL: debug

kakao:
  client-id: YOUR_KAKAO_CLIENT_ID
  client-secret: YOUR_KAKAO_CLIENT_SECRET
  redirect-uri: YOUR_REDIRECT_URI
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret: ${JWT_SECRET}
